

# optimization related
grad_clip: 5.0
batch_type: length
batch_bins: 2000000
accum_grad: 1
max_epoch: 15  # 15epoch is enougth

optim: adam
optim_conf:
   lr: 0.001
scheduler: warmuplr
scheduler_conf:
   warmup_steps: 30000

best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 10  # 10 is good.
