# minibatch related
batch_type: length
batch_bins: 2000000  
accum_grad: 2
grad_clip: 5
max_epoch: 70
patience: 3
# The initialization method for model parameters
init: xavier_uniform
normalize: none
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - acc
    - max
-   - train
    - loss
    - min
keep_nbest_models: 10
num_att_plot: 0

# network architecture
encoder: lstm
decoder: conv
decoder_conf:
    channel: 256
    kernel_size: 40
    stride: 20
    
model_conf:
    use_nawrn: true
    use_adaptive_weight: true
    use_ratio_two_branch: true


criterions:
  # The first criterion
  - name: mse
    conf:
        mask_type: IAM
        compute_on_mask: false
    # the wrapper for the current criterion
    # for single-talker case, we simplely use fixed_order wrapper
    wrapper: fixed_order
    wrapper_conf:
        weight: 1.0

optim: adam
optim_conf:
    lr: 0.001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 30000
