# minibatch related
batch_type: length
batch_bins: 2000000  
accum_grad: 2
grad_clip: 5
max_epoch: 80
patience: 10
# The initialization method for model parameters
init: xavier_uniform
normalize: none
val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - acc
    - max
-   - train
    - loss
    - min
keep_nbest_models: 10
num_att_plot: 0

# network architecture
enh_encoder: lstm
enh_decoder: conv
enh_decoder_conf:
    channel: 256
    kernel_size: 40
    stride: 20
    


enh_criterions:
  # The first criterion
  - name: mse
    conf:
        mask_type: IAM
        compute_on_mask: True
    # the wrapper for the current criterion
    # for single-talker case, we simplely use fixed_order wrapper
    wrapper: fixed_order
    wrapper_conf:
        weight: 1.0


frontend: none
# encoder related
asr_encoder: transformer
asr_encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    attention_dropout_rate: 0.0
    positional_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true

# decoder related
asr_decoder: transformer
asr_decoder_conf:
    input_layer: embed
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

asr_model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false
    extract_feats_in_collect_stats: false

model_conf:
    bypass_enh_prob: 0.0

optim: adam
optim_conf:
    lr: 0.001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 30000
